### ISSUE TITLE
Thanks for writing this plugin !

### ISSUE THREAD

**Issue by stephanenicolas** [hcoles/classycle-maven-plugin#1] opened 2013-04-06 12:05 UTC
I was gonna start writing one when I saw yours. Thank you very much for this effort.
I wish to add it to this project : https://github.com/stephanenicolas/Quality-Tools-for-Android.

I wil give you some feedback on it asap.

**Comment by stephanenicolas** [comment] 2013-04-06 12:45
My first feedback is that you should mention on your README.MD: 
- a sample configuration for the different mojos. 
- a warning about JDK 1.7 : this plugin expect JDK 1.7 to be the default JDK. This is not the case for mac os X users for instance. If people  receive an execption of type `Unsupported major.minor version 51.0`, it means that their default JDK/JRE is lower than 1.7. For mac users, they will need to download and install JDK 1.7 and point their `JAVA_HOME` environment variable to it like : 

``` bash
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_10.jdk/Contents/Home
```

**Comment by hcoles** [comment] 2013-04-06 13:51
Hi Stephane - thanks for the feedback.

I knocked this together with the plan to fix the chaotic package structure of my main project (http://pitest.org). I found that classycle isn't a great tool when you have existing large cycles, and ended up writing highwheel which you might also want to look at. Highwheel can't currently enforce structural rules, but does generate useful visualisations - particularly if you have large cycles.

As for Java 7 - that sounds like a build bug. It shouldn't need anything above 1.5. I'll push a new release out when I get chance.

**Comment by hcoles** [comment] 2013-04-06 14:08
Just checked - the pom has the target correctly set to 1.5 and the plugin works for me using openjdk 1.6. Are you able to provide an example project that reproduces the problem?

**Comment by stephanenicolas** [comment] 2013-04-06 14:19
Hi @hcoles ,

I achieved to make the plugin work quite easily. The check goal works like a charm an my android project.

The only problem I faced was this JDK version bug. I don't know what to say to reproduce it : with JAVA_HOME pointing at JDK 1.6 it fails with the given error and works with JDK 1.7. I don't figure out what examples I could give as it seems to work for you. 

Nevertheless, I will include this plugin in the QAT project and will tell you when it's ready, so maybe you can reproduce the problem with it.

**Comment by stephanenicolas** [comment] 2013-04-06 16:30
Hi @hcoles ,

I have put an example on GitHub : https://github.com/stephanenicolas/Quality-Tools-for-Android.

Here are the steps to reproduce the problem : 
1. clone the project. 
2. use java 1.6 
3. compile the project using the plugin 

```
git clone git@github.com:stephanenicolas/Quality-Tools-for-Android.git
export JAVA_HOME=/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/
mvn clean compile -P cycle
```

You should get an exception : 

```
java.lang.UnsupportedClassVersionError: classycle/util/StringPattern : Unsupported major.minor version 51.0
```

To solve the problem, use JDK 1.7 and recompile the project: 

```
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_10.jdk/Contents/Home
compile the project using the plugin 
```

Maven-compiler-plugin is set to source = target= 1.5.

**Comment by hcoles** [comment] 2013-04-23 07:58
Ok, had chance to look at this now.

The build of classycle on maven central that the plugin depends on looks to have been built on 1.7. I'm not clear on how it managed to run on 1.6 for me.

I'll embed a 1.5 or 1.6 compatible build and re-release.

**Comment by stephanenicolas** [comment] 2013-05-01 10:30
Thanks. Please, get me notified when you do so.

Stéphane

2013/4/23 hcoles notifications@github.com

> Ok, had chance to look at this now.
> 
> The build of classycle on maven central that the plugin depends on looks
> to have been built on 1.7. I'm not clear on how it managed to run on 1.6
> for me.
> 
> I'll embed a 1.5 or 1.6 compatible build and re-release.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hcoles/classycle-maven-plugin/issues/1#issuecomment-16844415
> .

## 

Stéphane _NICOLAS_,
_OCTO Technology_
Développeur & Consultant Android / Java
..........................................................
50, Avenue des Champs-Elysées
75008 Paris
+33 (0)6.26.32.34.09
www.octo.com - blog.octo.com
www.usievents.com
...........................................................

**Comment by achingbrain** [comment] 2014-02-11 12:14
Did you ever get a chance to release a version with JDK < 7 compatibility?  It looks like the version in Maven Central (0.2) still requires JDK 7.

**Comment by stephanenicolas** [comment] 2014-02-11 13:03
What présents you from switching to jdk 7 ?

**Comment by achingbrain** [comment] 2014-02-11 13:04
Policy. I don't agree with it but it's waaaay out of my control.

**Comment by hcoles** [comment] 2014-02-17 16:04
@achingbrain pull request has been merged in (thanks). The 0.3 release should sync across to maven central in the next 24 hours.

**Closed as completed by hcoles** 2014-02-17 16:04 UTC
